// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jabiezfpkfyzfpiswcwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphYmllemZwa2Z5emZwaXN3Y3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODczNzIsImV4cCI6MjA2NzY2MzM3Mn0.mo2y35i7vtSq8v8FR8eAM0KDzDXG8v5629B6FiPKalg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});